/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author kira
 */
public class JFrameVentanaSesion extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVentanaSesión
     */
    public JFrameVentanaSesion() {
        initComponents();
        setSize(1250, 700);
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAplicacion.png")).getImage());
        jTabbedPaneIniciaroRegistrar.setUI(null);
        jTabbedPaneIniciaroRegistrar.setBorder(null);
        jLabelTextoIniciarSesión.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 0, 0, 0)));
        jLabelTextoRegistrarse.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 0, 0, 0)));
        jLabelSalirPrograma.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0, 0, 0, 0)));
        jButtonAccederIn.setContentAreaFilled(false);
        jButtonAccederIn.setOpaque(true);
        jButtonRegistrarseRe.setContentAreaFilled(false);
        jButtonRegistrarseRe.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelInicRegis = new javax.swing.JPanel();
        jLabelTextoIniciarSesión = new javax.swing.JLabel();
        jLabelTextoRegistrarse = new javax.swing.JLabel();
        jTabbedPaneIniciaroRegistrar = new javax.swing.JTabbedPane();
        jPanelIniciarSesion = new javax.swing.JPanel();
        jTextFieldUsuarioIn = new javax.swing.JTextField();
        jButtonAccederIn = new javax.swing.JButton();
        jPasswordFieldContraseñaUsuarioIn = new javax.swing.JPasswordField();
        jPanelRegistrarse = new javax.swing.JPanel();
        jTextFieldUsuarioRe = new javax.swing.JTextField();
        jPasswordFielUsuarioRe = new javax.swing.JPasswordField();
        jButtonRegistrarseRe = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabelNombreApp = new javax.swing.JLabel();
        jLabelSalirPrograma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JustPlay");
        setMaximumSize(new java.awt.Dimension(1250, 700));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(30, 30, 30));

        jPanelInicRegis.setBackground(new java.awt.Color(46, 47, 51));

        jLabelTextoIniciarSesión.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabelTextoIniciarSesión.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoIniciarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoIniciarSesión.setText("INICIAR SESIÓN");
        jLabelTextoIniciarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelTextoRegistrarse.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabelTextoRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoRegistrarse.setText("REGISTRARSE");
        jLabelTextoRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTabbedPaneIniciaroRegistrar.setBackground(new java.awt.Color(44, 44, 44));

        jPanelIniciarSesion.setBackground(new java.awt.Color(46, 47, 51));

        jTextFieldUsuarioIn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextFieldUsuarioIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuarioIn.setBorder(null);
        jTextFieldUsuarioIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioInActionPerformed(evt);
            }
        });

        jButtonAccederIn.setBackground(new java.awt.Color(126, 54, 240));
        jButtonAccederIn.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jButtonAccederIn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAccederIn.setText("ACCEDER");
        jButtonAccederIn.setBorder(null);
        jButtonAccederIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAccederIn.setFocusPainted(false);

        jPasswordFieldContraseñaUsuarioIn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPasswordFieldContraseñaUsuarioIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldContraseñaUsuarioIn.setBorder(null);

        javax.swing.GroupLayout jPanelIniciarSesionLayout = new javax.swing.GroupLayout(jPanelIniciarSesion);
        jPanelIniciarSesion.setLayout(jPanelIniciarSesionLayout);
        jPanelIniciarSesionLayout.setHorizontalGroup(
            jPanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldUsuarioIn)
            .addComponent(jPasswordFieldContraseñaUsuarioIn)
            .addComponent(jButtonAccederIn, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        jPanelIniciarSesionLayout.setVerticalGroup(
            jPanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIniciarSesionLayout.createSequentialGroup()
                .addComponent(jTextFieldUsuarioIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldContraseñaUsuarioIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAccederIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPaneIniciaroRegistrar.addTab("IniciarSesión", jPanelIniciarSesion);

        jPanelRegistrarse.setBackground(new java.awt.Color(46, 47, 51));

        jTextFieldUsuarioRe.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextFieldUsuarioRe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuarioRe.setBorder(null);

        jPasswordFielUsuarioRe.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPasswordFielUsuarioRe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFielUsuarioRe.setBorder(null);

        jButtonRegistrarseRe.setBackground(new java.awt.Color(126, 54, 240));
        jButtonRegistrarseRe.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jButtonRegistrarseRe.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarseRe.setText("REGISTRARSE");
        jButtonRegistrarseRe.setBorder(null);
        jButtonRegistrarseRe.setFocusPainted(false);
        jButtonRegistrarseRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseReActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarseLayout = new javax.swing.GroupLayout(jPanelRegistrarse);
        jPanelRegistrarse.setLayout(jPanelRegistrarseLayout);
        jPanelRegistrarseLayout.setHorizontalGroup(
            jPanelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldUsuarioRe)
            .addComponent(jPasswordFielUsuarioRe)
            .addComponent(jButtonRegistrarseRe, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        jPanelRegistrarseLayout.setVerticalGroup(
            jPanelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarseLayout.createSequentialGroup()
                .addComponent(jTextFieldUsuarioRe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFielUsuarioRe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrarseRe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPaneIniciaroRegistrar.addTab("Registrarse", jPanelRegistrarse);

        jLabelIcono.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelIcono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIcono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLoginRegister3.png"))); // NOI18N

        jLabelNombreApp.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabelNombreApp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombreApp.setText("JustPlay");

        jLabelSalirPrograma.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabelSalirPrograma.setForeground(new java.awt.Color(141, 142, 146));
        jLabelSalirPrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalirPrograma.setText("Salir del programa");
        jLabelSalirPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelInicRegisLayout = new javax.swing.GroupLayout(jPanelInicRegis);
        jPanelInicRegis.setLayout(jPanelInicRegisLayout);
        jPanelInicRegisLayout.setHorizontalGroup(
            jPanelInicRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicRegisLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanelInicRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPaneIniciaroRegistrar)
                    .addGroup(jPanelInicRegisLayout.createSequentialGroup()
                        .addComponent(jLabelTextoIniciarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTextoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInicRegisLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombreApp)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicRegisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSalirPrograma)
                .addGap(141, 141, 141))
        );
        jPanelInicRegisLayout.setVerticalGroup(
            jPanelInicRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicRegisLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanelInicRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelInicRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoIniciarSesión)
                    .addComponent(jLabelTextoRegistrarse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneIniciaroRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSalirPrograma)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jPanelInicRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanelInicRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarseReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseReActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarseReActionPerformed

    private void jTextFieldUsuarioInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVentanaSesion().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccederIn;
    private javax.swing.JButton jButtonRegistrarseRe;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelNombreApp;
    private javax.swing.JLabel jLabelSalirPrograma;
    private javax.swing.JLabel jLabelTextoIniciarSesión;
    private javax.swing.JLabel jLabelTextoRegistrarse;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelInicRegis;
    private javax.swing.JPanel jPanelIniciarSesion;
    private javax.swing.JPanel jPanelRegistrarse;
    private javax.swing.JPasswordField jPasswordFielUsuarioRe;
    private javax.swing.JPasswordField jPasswordFieldContraseñaUsuarioIn;
    private javax.swing.JTabbedPane jTabbedPaneIniciaroRegistrar;
    private javax.swing.JTextField jTextFieldUsuarioIn;
    private javax.swing.JTextField jTextFieldUsuarioRe;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonAccederIn() {
        return jButtonAccederIn;
    }

    public JButton getjButtonRegistrarseRe() {
        return jButtonRegistrarseRe;
    }

    public JLabel getjLabelIcono() {
        return jLabelIcono;
    }

    public JLabel getjLabelNombreApp() {
        return jLabelNombreApp;
    }

    public JLabel getjLabelSalirPrograma() {
        return jLabelSalirPrograma;
    }

    public JLabel getjLabelTextoIniciarSesión() {
        return jLabelTextoIniciarSesión;
    }

    public JLabel getjLabelTextoRegistrarse() {
        return jLabelTextoRegistrarse;
    }

    public JPanel getjPanelFondo() {
        return jPanelFondo;
    }

    public JPanel getjPanelInicRegis() {
        return jPanelInicRegis;
    }

    public JPanel getjPanelIniciarSesion() {
        return jPanelIniciarSesion;
    }

    public JPanel getjPanelRegistrarse() {
        return jPanelRegistrarse;
    }

    public JPasswordField getjPasswordFielUsuarioRe() {
        return jPasswordFielUsuarioRe;
    }

    public JPasswordField getjPasswordFieldContraseñaUsuarioIn() {
        return jPasswordFieldContraseñaUsuarioIn;
    }

    public JTabbedPane getjTabbedPaneIniciaroRegistrar() {
        return jTabbedPaneIniciaroRegistrar;
    }

    public JTextField getjTextFieldUsuarioIn() {
        return jTextFieldUsuarioIn;
    }

    public JTextField getjTextFieldUsuarioRe() {
        return jTextFieldUsuarioRe;
    }

}
